platformName=Android
automationName=UiAutomator2
deviceName=emulator-5554
app=src/test/resources/app-debug.apk
appium:udid=emulator-5554
appium:fullReset=false
appium:noReset=false
appium:autoGrantPermissions=true
appium:appWaitActivity=com.example.myapplication.MainActivity
