appium:deviceName=Pixel_5_API_34
appium:udid=emulator-5554
appium:platformVersion=14
appium:fullReset=false
app=../apk/app-debug.apk
appium:autoGrantPermissions=true
appium:forceEspressoRebuild=false
appium:allowTestPackages=true