platformName=Android
deviceName=emulator-5554
app=src/test/resources/app-debug.apk
automationName=Espresso
appium:udid=emulator-5554
appium:fullReset=false
appium:noReset=false
appium:autoGrantPermissions=true
appium:forceEspressoRebuild=false
appium:allowTestPackages=true
