plugins {
    id 'java'
    id 'se.thinkcode.cucumber-runner' version '0.0.12'
    id 'com.github.spacialcircumstances.gradle-cucumber-reporting' version '0.1.25'
}

group = 'salad'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation fileTree(dir: 'libs', include: ['*.jar'])

    // BOMs for consistent dependency versions
    testImplementation platform('org.junit:junit-bom:6.0.1')
    testImplementation platform('io.cucumber:cucumber-bom:7.31.0')

    // Cucumber + JUnit Platform
    testImplementation 'io.cucumber:cucumber-java'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine'
    testImplementation 'org.junit.platform:junit-platform-suite'
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

cucumber {
    main = 'io.cucumber.core.cli.Main'
    glue = 'classpath:android'
    plugin = [
            'pretty',
            'json:target/report.json'
    ]
}

cucumberReports {
    outputDir = file('target/report')
    reports = files('target/report.json')
}

tasks.register('rerunCucumber') {
    doLast {
        javaexec {
            mainClass.set('io.cucumber.core.cli.Main')
            classpath = configurations.testRuntimeClasspath +
                    sourceSets.main.output +
                    sourceSets.test.output

            systemProperties = System.getProperties().collectEntries { key, value ->
                [(key.toString()): value.toString()]
            }

            args = [
                    '@rerun/failed_scenarios.txt',
                    '--plugin', 'pretty',
                    '--plugin', 'json:target/report.json',
                    '--plugin', 'rerun:rerun/failed_scenarios.txt',
                    '--glue', 'android',
            ]
        }
    }
}


test {
    useJUnitPlatform()
}
